name: package

on:
  push:

jobs:
  package:
    name: Package Project
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Create executable
        run: |
          python -m pip install --upgrade pip;
          pip install -r requirements.txt;
          chmod a+x src/main/main.py
          echo "Test Executable"
          ./src/main/main.py amd64
      - name: Create Tarball
        run: |
          tar -czvf project.tar.gz .
          ls -la
      - name: Upload Tar
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            project.tar.gz
              

