name: Code Test

on:
  workflow_dispatch:
    inputs:
      architecture:
        default: "amd64"
        description: debian architecture to get pkg stats for
jobs:
  get-statistics:
    runs-on: ubuntu-latest
    env:
      ARCH:  ${{ github.event.inputs.architecture }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install python requirements
      run: |
          python -m pip install --upgrade pip;
          pip install -r requirements.txt;
    - name: Get Package Info
      run: |
        python3 src/main/main.py $ARCH
